17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:31:17 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
17-01-2023 13:32:30 - www.giuseppeamato.eu - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
